### ISSUE TITLE
Update Registration Form

### ISSUE THREAD

**Issue by Rian501** [code-for-nashville/glean-tennessee-web#42] opened 2018-11-04 00:36 UTC
Add items missing from registration form (from the roadmap - Farmer Registers
The following fields must be available to register a new farmer

*name
*address
*phone
is_organic
availability schedule (for example, not available during CSA pickup)
additional notes)

**Comment by floatingman** [comment] 2018-11-17 16:00
I can jump on this issue

**Comment by CoreyAR** [comment] 2019-03-12 08:41
I believe this is a duplicate of #13 . I am going to close in favor of that ticket because it has more details.

**Closed by CoreyAR** 2019-03-12 08:41 UTC
Labels: enhancement, good first issue
